apiVersion: v1
kind: Service
metadata:
  namespace: ns-mytodoapp
  name: todoapp-service
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30023
  type: NodePort
